name: "Workflow Commands"

on: ["push"]
job:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "Group Logggin"
        run: |
          echo "::group::My Group Message"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
